export enum enum_formatoColuna {
    nenhum = 0,
    numero = 1,
    data = 2,
    dataHora = 3,
    moeda = 4,
    texto = 5,
    booleano = 6,
    cpf = 7,
    cnpj = 8,
    numero_sem_formato = 9,
    decimal_1 = 10,
    decimal_2 = 11,
    decimal_3 = 12,
    decimal_4 = 13,
}